part of health;

/// List of all available data types.
enum HealthDataType {
  ACTIVE_ENERGY_BURNED,
  BASAL_ENERGY_BURNED,
  BLOOD_GLUCOSE,
  BLOOD_OXYGEN,
  BLOOD_PRESSURE_DIASTOLIC,
  BLOOD_PRESSURE_SYSTOLIC,
  BODY_FAT_PERCENTAGE,
  BODY_MASS_INDEX,
  BODY_TEMPERATURE,
  HEART_RATE,
  HEART_RATE_VARIABILITY_SDNN,
  HEIGHT,
  RESTING_HEART_RATE,
  STEPS,
  WAIST_CIRCUMFERENCE,
  WALKING_HEART_RATE,
  WEIGHT,
  DISTANCE_WALKING_RUNNING,
  FLIGHTS_CLIMBED,
  MOVE_MINUTES,
  DISTANCE_DELTA,
  MINDFULNESS,
  WATER,
  SLEEP_IN_BED,
  SLEEP_ASLEEP,
  SLEEP_AWAKE,
  DISTANCE_CYCLING,
  PUSH_COUNT,
  DISTANCE_WHEELCHAIR,
  SWIMMING_STROKE_COUNT,
  DISTANCE_SWIMMING,
  DISTANCE_DOWNGHILL_SNOW_SPORTS,
  NIKE_FUEL,
  APPLE_EXERCISE_TIME,
  APPLE_STAND_HOUR,
  APPLE_STAND_TIME,
  VO2_MAX,
  LOW_CARDIO_FITNESS_EVENT,
  BODY_MASS,
  LEAN_BODY_MASS,
  BASAL_BODY_TEMPERATURE,
  CERVICAL_MUCUS_QUALITY,
  SEXUAL_ACTIVITY,
  ENVIRONMENTAL_AUDIO_EXPOSURE,
  HEADPHONE_AUDIO_EXPOSURE,
  RESPIRATORY_RATE,
  BLOOD_ALCOHOL_CONTENT,
  SIX_MINUTE_WALK_TEST_DISTANCE,
  WALKING_SPEED,
  WALKING_STEP_LENGTH,
  WALKING_ASYMMETRY_PERCENTAGE,
  WALKING_DOUBLE_SUPPORT_PERCENTAGE,
  STAIR_ASCENT_SPEED,
  STAIR_DESCENT_SPEED,
  HANDWASHING_EVENT,
  UV_EXPOSURE,

// Activity duration
  WALKING_RUNNING_DURATION,
  CYCLING_DURATION,
  SWIMMING_DURATION,

// Heart Rate events (specific to Apple Watch)
  HIGH_HEART_RATE_EVENT,
  LOW_HEART_RATE_EVENT,
  IRREGULAR_HEART_RATE_EVENT,
  ELECTRODERMAL_ACTIVITY,

// Nutrition health-types
  DIETARY_ENERGY_CONSUMED,
  DIETARY_FAT_TOTAL,
  DIETARY_FAT_SATURATED,
  DIETARY_CHOLESTEROL,
  DIETARY_CARBOHYDRATES,
  DIETARY_FIBER,
  DIETARY_SUGAR,
  DIETARY_PROTEIN,
  DIETARY_CALCIUM,
  DIETARY_IRON,
  DIETARY_POTASSIUM,
  DIETARY_SODIUM,
  DIETARY_VITAMIN_A,
  DIETARY_VITAMIN_C,
  DIETARY_VITAMIN_D,
}

/// List of data types available on iOS
const List<HealthDataType> _dataTypeKeysIOS = [
  HealthDataType.ACTIVE_ENERGY_BURNED,
  HealthDataType.BASAL_ENERGY_BURNED,
  HealthDataType.BLOOD_GLUCOSE,
  HealthDataType.BLOOD_OXYGEN,
  HealthDataType.BLOOD_PRESSURE_DIASTOLIC,
  HealthDataType.BLOOD_PRESSURE_SYSTOLIC,
  HealthDataType.BODY_FAT_PERCENTAGE,
  HealthDataType.BODY_MASS_INDEX,
  HealthDataType.BODY_TEMPERATURE,
  HealthDataType.ELECTRODERMAL_ACTIVITY,
  HealthDataType.HEART_RATE,
  HealthDataType.HEART_RATE_VARIABILITY_SDNN,
  HealthDataType.HEIGHT,
  HealthDataType.HIGH_HEART_RATE_EVENT,
  HealthDataType.IRREGULAR_HEART_RATE_EVENT,
  HealthDataType.LOW_HEART_RATE_EVENT,
  HealthDataType.RESTING_HEART_RATE,
  HealthDataType.STEPS,
  HealthDataType.WAIST_CIRCUMFERENCE,
  HealthDataType.WALKING_HEART_RATE,
  HealthDataType.WEIGHT,
  HealthDataType.FLIGHTS_CLIMBED,
  HealthDataType.DISTANCE_WALKING_RUNNING,
  HealthDataType.MINDFULNESS,
  HealthDataType.SLEEP_IN_BED,
  HealthDataType.SLEEP_AWAKE,
  HealthDataType.SLEEP_ASLEEP,
  HealthDataType.WATER,
  HealthDataType.DISTANCE_CYCLING,
  HealthDataType.PUSH_COUNT,
  HealthDataType.DISTANCE_WHEELCHAIR,
  HealthDataType.SWIMMING_STROKE_COUNT,
  HealthDataType.DISTANCE_SWIMMING,
  HealthDataType.DISTANCE_DOWNGHILL_SNOW_SPORTS,
  HealthDataType.NIKE_FUEL,
  HealthDataType.APPLE_EXERCISE_TIME,
  HealthDataType.APPLE_STAND_HOUR,
  HealthDataType.APPLE_STAND_TIME,
  HealthDataType.VO2_MAX,
  HealthDataType.LOW_CARDIO_FITNESS_EVENT,
  HealthDataType.BODY_MASS,
  HealthDataType.LEAN_BODY_MASS,
  HealthDataType.BASAL_BODY_TEMPERATURE,
  HealthDataType.CERVICAL_MUCUS_QUALITY,
  HealthDataType.SEXUAL_ACTIVITY,
  HealthDataType.ENVIRONMENTAL_AUDIO_EXPOSURE,
  HealthDataType.HEADPHONE_AUDIO_EXPOSURE,
  HealthDataType.RESPIRATORY_RATE,
  HealthDataType.BLOOD_ALCOHOL_CONTENT,
  HealthDataType.SIX_MINUTE_WALK_TEST_DISTANCE,
  HealthDataType.WALKING_SPEED,
  HealthDataType.WALKING_STEP_LENGTH,
  HealthDataType.WALKING_ASYMMETRY_PERCENTAGE,
  HealthDataType.WALKING_DOUBLE_SUPPORT_PERCENTAGE,
  HealthDataType.STAIR_ASCENT_SPEED,
  HealthDataType.STAIR_DESCENT_SPEED,
  HealthDataType.HANDWASHING_EVENT,
  HealthDataType.UV_EXPOSURE,
  HealthDataType.WALKING_RUNNING_DURATION,
  HealthDataType.CYCLING_DURATION,
  HealthDataType.SWIMMING_DURATION,
  HealthDataType.DIETARY_ENERGY_CONSUMED,
  HealthDataType.DIETARY_FAT_TOTAL,
  HealthDataType.DIETARY_FAT_SATURATED,
  HealthDataType.DIETARY_CHOLESTEROL,
  HealthDataType.DIETARY_CARBOHYDRATES,
  HealthDataType.DIETARY_FIBER,
  HealthDataType.DIETARY_SUGAR,
  HealthDataType.DIETARY_PROTEIN,
  HealthDataType.DIETARY_CALCIUM,
  HealthDataType.DIETARY_IRON,
  HealthDataType.DIETARY_POTASSIUM,
  HealthDataType.DIETARY_SODIUM,
  HealthDataType.DIETARY_VITAMIN_A,
  HealthDataType.DIETARY_VITAMIN_C,
  HealthDataType.DIETARY_VITAMIN_D,
];

/// List of data types available on Android
const List<HealthDataType> _dataTypeKeysAndroid = [
  HealthDataType.ACTIVE_ENERGY_BURNED,
  HealthDataType.BLOOD_GLUCOSE,
  HealthDataType.BLOOD_OXYGEN,
  HealthDataType.BLOOD_PRESSURE_DIASTOLIC,
  HealthDataType.BLOOD_PRESSURE_SYSTOLIC,
  HealthDataType.BODY_FAT_PERCENTAGE,
  HealthDataType.BODY_MASS_INDEX,
  HealthDataType.BODY_TEMPERATURE,
  HealthDataType.HEART_RATE,
  HealthDataType.HEIGHT,
  HealthDataType.STEPS,
  HealthDataType.WEIGHT,
  HealthDataType.MOVE_MINUTES,
  HealthDataType.DISTANCE_DELTA,
  HealthDataType.SLEEP_AWAKE,
  HealthDataType.SLEEP_ASLEEP,
  HealthDataType.WATER,
];

/// Map a [HealthDataType] to a [HealthDataUnit].
const Map<HealthDataType, HealthDataUnit> _dataTypeToUnit = {
  HealthDataType.ACTIVE_ENERGY_BURNED: HealthDataUnit.CALORIES,
  HealthDataType.BASAL_ENERGY_BURNED: HealthDataUnit.CALORIES,
  HealthDataType.BLOOD_GLUCOSE: HealthDataUnit.MILLIGRAM_PER_DECILITER,
  HealthDataType.BLOOD_OXYGEN: HealthDataUnit.PERCENTAGE,
  HealthDataType.BLOOD_PRESSURE_DIASTOLIC: HealthDataUnit.MILLIMETER_OF_MERCURY,
  HealthDataType.BLOOD_PRESSURE_SYSTOLIC: HealthDataUnit.MILLIMETER_OF_MERCURY,
  HealthDataType.BODY_FAT_PERCENTAGE: HealthDataUnit.PERCENTAGE,
  HealthDataType.BODY_MASS_INDEX: HealthDataUnit.NO_UNIT,
  HealthDataType.BODY_TEMPERATURE: HealthDataUnit.DEGREE_CELSIUS,
  HealthDataType.ELECTRODERMAL_ACTIVITY: HealthDataUnit.SIEMENS,
  HealthDataType.HEART_RATE: HealthDataUnit.BEATS_PER_MINUTE,
  HealthDataType.HEIGHT: HealthDataUnit.METERS,
  HealthDataType.RESTING_HEART_RATE: HealthDataUnit.BEATS_PER_MINUTE,
  HealthDataType.STEPS: HealthDataUnit.COUNT,
  HealthDataType.WAIST_CIRCUMFERENCE: HealthDataUnit.METERS,
  HealthDataType.WALKING_HEART_RATE: HealthDataUnit.BEATS_PER_MINUTE,
  HealthDataType.WEIGHT: HealthDataUnit.KILOGRAMS,
  HealthDataType.DISTANCE_WALKING_RUNNING: HealthDataUnit.METERS,
  HealthDataType.FLIGHTS_CLIMBED: HealthDataUnit.COUNT,
  HealthDataType.MOVE_MINUTES: HealthDataUnit.MINUTES,
  HealthDataType.DISTANCE_DELTA: HealthDataUnit.METERS,
  HealthDataType.DISTANCE_CYCLING: HealthDataUnit.METERS,
  HealthDataType.PUSH_COUNT: HealthDataUnit.COUNT,
  HealthDataType.DISTANCE_WHEELCHAIR: HealthDataUnit.METERS,
  HealthDataType.SWIMMING_STROKE_COUNT: HealthDataUnit.COUNT,
  HealthDataType.DISTANCE_SWIMMING: HealthDataUnit.METERS,
  HealthDataType.DISTANCE_DOWNGHILL_SNOW_SPORTS: HealthDataUnit.METERS,
  HealthDataType.NIKE_FUEL: HealthDataUnit.COUNT,
  HealthDataType.APPLE_EXERCISE_TIME: HealthDataUnit.MINUTES,
  HealthDataType.APPLE_STAND_HOUR: HealthDataUnit.NO_UNIT,
  HealthDataType.APPLE_STAND_TIME: HealthDataUnit.MINUTES,
  HealthDataType.VO2_MAX: HealthDataUnit.MILLILITER_PER_KILOGRAM_PER_MINUTE,
  HealthDataType.LOW_CARDIO_FITNESS_EVENT: HealthDataUnit.NO_UNIT,
  HealthDataType.BODY_MASS: HealthDataUnit.KILOGRAMS,
  HealthDataType.LEAN_BODY_MASS: HealthDataUnit.KILOGRAMS,
  HealthDataType.BASAL_BODY_TEMPERATURE: HealthDataUnit.DEGREE_CELSIUS,
  HealthDataType.CERVICAL_MUCUS_QUALITY: HealthDataUnit.NO_UNIT,
  HealthDataType.SEXUAL_ACTIVITY: HealthDataUnit.NO_UNIT,
  HealthDataType.ENVIRONMENTAL_AUDIO_EXPOSURE: HealthDataUnit.PASCAL,
  HealthDataType.HEADPHONE_AUDIO_EXPOSURE: HealthDataUnit.PASCAL,
  HealthDataType.RESPIRATORY_RATE: HealthDataUnit.COUNTS_PER_MINUTE,
  HealthDataType.BLOOD_ALCOHOL_CONTENT: HealthDataUnit.PERCENTAGE,
  HealthDataType.SIX_MINUTE_WALK_TEST_DISTANCE: HealthDataUnit.METERS,
  HealthDataType.WALKING_SPEED: HealthDataUnit.KILOMETERS_PER_HOUR,
  HealthDataType.WALKING_STEP_LENGTH: HealthDataUnit.METERS,
  HealthDataType.WALKING_ASYMMETRY_PERCENTAGE: HealthDataUnit.PERCENTAGE,
  HealthDataType.WALKING_DOUBLE_SUPPORT_PERCENTAGE: HealthDataUnit.PERCENTAGE,
  HealthDataType.STAIR_ASCENT_SPEED: HealthDataUnit.KILOMETERS_PER_HOUR,
  HealthDataType.STAIR_DESCENT_SPEED: HealthDataUnit.KILOMETERS_PER_HOUR,
  HealthDataType.HANDWASHING_EVENT: HealthDataUnit.NO_UNIT,
  HealthDataType.UV_EXPOSURE: HealthDataUnit.COUNT,
  HealthDataType.WALKING_RUNNING_DURATION: HealthDataUnit.MINUTES,
  HealthDataType.CYCLING_DURATION: HealthDataUnit.MINUTES,
  HealthDataType.SWIMMING_DURATION: HealthDataUnit.MINUTES,

  HealthDataType.WATER: HealthDataUnit.LITER,
  HealthDataType.SLEEP_IN_BED: HealthDataUnit.MINUTES,
  HealthDataType.SLEEP_ASLEEP: HealthDataUnit.MINUTES,
  HealthDataType.SLEEP_AWAKE: HealthDataUnit.MINUTES,
  HealthDataType.MINDFULNESS: HealthDataUnit.MINUTES,

  /// Heart Rate events (specific to Apple Watch)
  HealthDataType.HIGH_HEART_RATE_EVENT: HealthDataUnit.NO_UNIT,
  HealthDataType.LOW_HEART_RATE_EVENT: HealthDataUnit.NO_UNIT,
  HealthDataType.IRREGULAR_HEART_RATE_EVENT: HealthDataUnit.NO_UNIT,
  HealthDataType.HEART_RATE_VARIABILITY_SDNN: HealthDataUnit.MILLISECONDS,

  /// Nutrition health-types
  HealthDataType.DIETARY_ENERGY_CONSUMED: HealthDataUnit.CALORIES,
  HealthDataType.DIETARY_FAT_TOTAL: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_FAT_SATURATED: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_CHOLESTEROL: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_CARBOHYDRATES: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_FIBER: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_SUGAR: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_PROTEIN: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_CALCIUM: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_IRON: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_POTASSIUM: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_SODIUM: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_VITAMIN_A: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_VITAMIN_C: HealthDataUnit.KILOGRAMS,
  HealthDataType.DIETARY_VITAMIN_D: HealthDataUnit.KILOGRAMS,
};

const HealthDataTypeJsonValue = {
  HealthDataType.ACTIVE_ENERGY_BURNED: 'active_energy_burned',
  HealthDataType.BASAL_ENERGY_BURNED: 'basal_energy_burned',
  HealthDataType.BLOOD_GLUCOSE: 'blood_glucose',
  HealthDataType.BLOOD_OXYGEN: 'blood_oxygen',
  HealthDataType.BLOOD_PRESSURE_DIASTOLIC: 'blood_pressure_diastolic',
  HealthDataType.BLOOD_PRESSURE_SYSTOLIC: 'blood_pressure_systolic',
  HealthDataType.BODY_FAT_PERCENTAGE: 'body_fat_percentage',
  HealthDataType.BODY_MASS_INDEX: 'body_mass_index',
  HealthDataType.BODY_TEMPERATURE: 'body_temperature',
  HealthDataType.HEART_RATE: 'heart_rate',
  HealthDataType.HEART_RATE_VARIABILITY_SDNN: 'heart_rate_variability_sdnn',
  HealthDataType.HEIGHT: 'height',
  HealthDataType.RESTING_HEART_RATE: 'resting_heart_rate',
  HealthDataType.STEPS: 'steps',
  HealthDataType.WAIST_CIRCUMFERENCE: 'waist_circumference',
  HealthDataType.WALKING_HEART_RATE: 'walking_heart_rate',
  HealthDataType.WEIGHT: 'weight',
  HealthDataType.DISTANCE_WALKING_RUNNING: 'distance_walking_running',
  HealthDataType.FLIGHTS_CLIMBED: 'flights_climbed',
  HealthDataType.MOVE_MINUTES: 'move_minutes',
  HealthDataType.DISTANCE_DELTA: 'distance_delta',
  HealthDataType.MINDFULNESS: 'mindfulness',
  HealthDataType.WATER: 'water',
  HealthDataType.SLEEP_IN_BED: 'sleep_in_bed',
  HealthDataType.SLEEP_ASLEEP: 'sleep_asleep',
  HealthDataType.SLEEP_AWAKE: 'sleep_awake',
  HealthDataType.HIGH_HEART_RATE_EVENT: 'high_heart_rate_event',
  HealthDataType.LOW_HEART_RATE_EVENT: 'low_heart_rate_event',
  HealthDataType.IRREGULAR_HEART_RATE_EVENT: 'irregular_heart_rate_event',
  HealthDataType.ELECTRODERMAL_ACTIVITY: 'electrodermal_activity',
  HealthDataType.DISTANCE_CYCLING: 'distance_cycling',
  HealthDataType.PUSH_COUNT: 'push_count',
  HealthDataType.DISTANCE_WHEELCHAIR: 'distance_wheelchair',
  HealthDataType.SWIMMING_STROKE_COUNT: 'swimming_stroke_count',
  HealthDataType.DISTANCE_SWIMMING: 'distance_swimming',
  HealthDataType.DISTANCE_DOWNGHILL_SNOW_SPORTS:
      'distance_downghill_snow_sports',
  HealthDataType.NIKE_FUEL: 'nike_fuel',
  HealthDataType.APPLE_EXERCISE_TIME: 'apple_exercise_time',
  HealthDataType.APPLE_STAND_HOUR: 'apple_stand_hour',
  HealthDataType.APPLE_STAND_TIME: 'apple_stand_time',
  HealthDataType.LOW_CARDIO_FITNESS_EVENT: 'low_cardio_fitness_event',
  HealthDataType.BODY_MASS: 'body_mass',
  HealthDataType.LEAN_BODY_MASS: 'lean_body_mass',
  HealthDataType.BASAL_BODY_TEMPERATURE: 'basal_body_temperature',
  HealthDataType.CERVICAL_MUCUS_QUALITY: 'cervical_mucus_quality',
  HealthDataType.SEXUAL_ACTIVITY: 'sexual_activity',
  HealthDataType.ENVIRONMENTAL_AUDIO_EXPOSURE: 'environmental_audio_exposure',
  HealthDataType.HEADPHONE_AUDIO_EXPOSURE: 'headphone_audio_exposure',
  HealthDataType.RESPIRATORY_RATE: 'respiratory_rate',
  HealthDataType.BLOOD_ALCOHOL_CONTENT: 'blood_alcohol_content',
  HealthDataType.SIX_MINUTE_WALK_TEST_DISTANCE: 'six_minute_walk_test_distance',
  HealthDataType.WALKING_SPEED: 'walking_speed',
  HealthDataType.WALKING_STEP_LENGTH: 'walking_step_length',
  HealthDataType.WALKING_ASYMMETRY_PERCENTAGE: 'walking_asymmetry_percentage',
  HealthDataType.WALKING_DOUBLE_SUPPORT_PERCENTAGE:
      'walking_double_support_percentage',
  HealthDataType.STAIR_ASCENT_SPEED: 'stair_ascent_speed',
  HealthDataType.STAIR_DESCENT_SPEED: 'stair_descent_speed',
  HealthDataType.HANDWASHING_EVENT: 'handwashing_event',
  HealthDataType.UV_EXPOSURE: 'uv_exposure',
  HealthDataType.WALKING_RUNNING_DURATION: 'walking_running_duration',
  HealthDataType.CYCLING_DURATION: 'cycling_duration',
  HealthDataType.SWIMMING_DURATION: 'swimming_duration',
  HealthDataType.VO2_MAX: 'vo2_max',
  HealthDataType.DIETARY_ENERGY_CONSUMED: 'dietary_energy_consumed',
  HealthDataType.DIETARY_FAT_TOTAL: 'dietary_fat_total',
  HealthDataType.DIETARY_FAT_SATURATED: 'dietary_fat_saturated',
  HealthDataType.DIETARY_CHOLESTEROL: 'dietary_cholesterol',
  HealthDataType.DIETARY_CARBOHYDRATES: 'dietary_carbohydrates',
  HealthDataType.DIETARY_FIBER: 'dietary_fiber',
  HealthDataType.DIETARY_SUGAR: 'dietary_sugar',
  HealthDataType.DIETARY_PROTEIN: 'dietary_protein',
  HealthDataType.DIETARY_CALCIUM: 'dietary_calcium',
  HealthDataType.DIETARY_IRON: 'dietary_iron',
  HealthDataType.DIETARY_POTASSIUM: 'dietary_potassium',
  HealthDataType.DIETARY_SODIUM: 'dietary_sodium',
  HealthDataType.DIETARY_VITAMIN_A: 'dietary_vitamin_a',
  HealthDataType.DIETARY_VITAMIN_C: 'dietary_vitamin_c',
  HealthDataType.DIETARY_VITAMIN_D: 'dietary_vitamin_d',
};

const HealthDataUnitJsonValue = {
  HealthDataUnit.BEATS_PER_MINUTE: 'beats_per_minute',
  HealthDataUnit.CALORIES: 'calories',
  HealthDataUnit.COUNT: 'count',
  HealthDataUnit.DEGREE_CELSIUS: 'degree_celsius',
  HealthDataUnit.KILOGRAMS: 'kilograms',
  HealthDataUnit.METERS: 'meters',
  HealthDataUnit.MILLIGRAM_PER_DECILITER: 'milligram_per_deciliter',
  HealthDataUnit.MILLIMETER_OF_MERCURY: 'millimeter_of_mercury',
  HealthDataUnit.MILLISECONDS: 'milliseconds',
  HealthDataUnit.MINUTES: 'minutes',
  HealthDataUnit.NO_UNIT: 'no_unit',
  HealthDataUnit.PERCENTAGE: 'percentage',
  HealthDataUnit.SIEMENS: 'siemens',
  HealthDataUnit.UNKNOWN_UNIT: 'unknown_unit',
  HealthDataUnit.LITER: 'liter',
};

const PlatformTypeJsonValue = {
  PlatformType.IOS: 'ios',
  PlatformType.ANDROID: 'android'
};
