part of '../health.dart';

/// List of all units.
enum HealthDataUnit {
  BEATS_PER_MINUTE,
  CALORIES,
  COUNT,
  DEGREE_CELSIUS,
  KILOGRAMS,
  METERS,
  MILLIGRAM_PER_DECILITER,
  MILLIMETER_OF_MERCURY,
  MILLISECONDS,
  MINUTES,
  NO_UNIT,
  PERCENTAGE,
  SIEMENS,
  UNKNOWN_UNIT,
  LITER,
  PASCAL,
  COUNTS_PER_MINUTE,
  KILOMETERS_PER_HOUR,
  MILLILITER_PER_KILOGRAM_PER_MINUTE,
}
